import './color-engine.js';

const ColorEngine = globalThis.ColorEngine;

const {
  rgbToXyz,
  xyzToRgb,
  xyzToLab,
  labToXyz,
  rgbToLab,
  labToRgb,
  labToLch,
  lchToLab,
  rgbToLch,
  lchToRgb,
  circularHueDelta,
  circularDistance,
  deltaE2000,
  computeFastSSIM,
  computeEdgePreservationScore,
  MATERIAL_KEYS,
  MATERIAL_LABELS,
  computeEdgeMap,
  computeEdgeSafetyMap,
  boxBlurMask,
  classifyPixelMaterial,
  extractMaterialProfiles,
  aggregateMaterialProfiles,
  estimateIlluminationField,
  interpolateIllumination,
  applyIlluminationCorrection,
  transferLocalMaterialColor,
  evaluateCompositeScore,
  optimizeParameters
} = ColorEngine;

export default ColorEngine;
export {
  rgbToXyz,
  xyzToRgb,
  xyzToLab,
  labToXyz,
  rgbToLab,
  labToRgb,
  labToLch,
  lchToLab,
  rgbToLch,
  lchToRgb,
  circularHueDelta,
  circularDistance,
  deltaE2000,
  computeFastSSIM,
  computeEdgePreservationScore,
  MATERIAL_KEYS,
  MATERIAL_LABELS,
  computeEdgeMap,
  computeEdgeSafetyMap,
  boxBlurMask,
  classifyPixelMaterial,
  extractMaterialProfiles,
  aggregateMaterialProfiles,
  estimateIlluminationField,
  interpolateIllumination,
  applyIlluminationCorrection,
  transferLocalMaterialColor,
  evaluateCompositeScore,
  optimizeParameters
};
